### ISSUE TITLE
Lab 1.4 Replica Items

### ISSUE THREAD

**Issue by ctauro** [couchbase/training-cs300-course#11]
"On the far right, you can also see that there are a 71.1k active items on the server and 0 replica items.. Unable to see "0 replica items".. Image after this line should be updated. Probably that image is from the previous version..

**Comment by chrishaynesusa** [comment]
Notice a few things there. The RAM usage on this single node is about 20-30% and the CPU usage is 7-10%. There is an Add Server button at the top right that we’ll explore in a future lab to grow the cluster.

On the far right, you can also see that there are a 71.1k active items on the server and 0 replica items.

refers to image above not below.
