### ISSUE TITLE
Lab 1.6  fts index directory

### ISSUE THREAD

**Issue by ctauro** [couchbase/training-cs300-course#14]
Lab 1.6 on the output of "sudo ls -alh /opt/couchbase/var/lib/couchbase/indexes", the output does not show @fts directory

**Comment by ctauro** [comment]
Lab 1.6 on the output of "sudo ls -alh /opt/couchbase/var/lib/couchbase/indexes", the output does not show @fts directory

**Comment by chrishaynesusa** [comment]
removed fts line from la -alh output.

**Comment by chrishaynesusa** [comment]
removed fts line from la -alh output.
